Bump pytest lowerbound to 3.6
Testruns on Python 2.7 had the following error during pip isntall:

ERROR: pytest-cov 2.7.1 has requirement pytest>=3.6,
but you'll have pytest 3.3.2 which is incompatible.

This caused problems during the test. Bumping the pytest version
resolves this.